import "/public/assets/css/style.css"
import "/public/assets/css/responsive.css"

import { Urbanist } from 'next/font/google'

const urbanist = Urbanist({
    weight: ['300', '400', '500', '600', '700','800','900'],
    subsets: ['latin'],
    variable: "--urbanist",
    display: 'swap',
})
export const metadata = {
    title: 'Bidzen | NFT Marketplace Next.js Template',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${urbanist.variable} body header-fixed`}>{children}</body>
        </html>
    )
}
